// <auto-generated />
using System;
using Dungeon.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dungeon.Api.Migrations
{
    [DbContext(typeof(DungeonDbContext))]
    partial class DungeonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Dungeon.Infrastructure.Entities.DungeonMapEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GoalX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StartX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DungeonMaps");
                });

            modelBuilder.Entity("Dungeon.Infrastructure.Entities.ObstacleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DungeonMapId")
                        .HasColumnType("TEXT");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DungeonMapId");

                    b.HasIndex("X", "Y", "DungeonMapId")
                        .HasDatabaseName("IX_Obstacles_Coordinates_MapId");

                    b.ToTable("Obstacles");
                });

            modelBuilder.Entity("Dungeon.Infrastructure.Entities.ObstacleEntity", b =>
                {
                    b.HasOne("Dungeon.Infrastructure.Entities.DungeonMapEntity", "DungeonMap")
                        .WithMany("Obstacles")
                        .HasForeignKey("DungeonMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungeonMap");
                });

            modelBuilder.Entity("Dungeon.Infrastructure.Entities.DungeonMapEntity", b =>
                {
                    b.Navigation("Obstacles");
                });
#pragma warning restore 612, 618
        }
    }
}
